name: release_artifacts
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5

jobs:
  release-artifacts:
    name: Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install chromium
        run: sudo apt install chromium-browser
      - name: Install xvfb + dependencies
        # https://stackoverflow.com/questions/60304251/unable-to-open-x-display-when-trying-to-run-google-chrome-on-centos-rhel-7-5
        run: |
          sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
          sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
          Xvfb -ac :99 -screen 0 1280x1024x16 &
      - run: chromium-browser --version
      - name: Build artifacts
        run: |
          cd ..
          ls -a
          DISPLAY=:99 chromium-browser --pack-extension=./chromeExtension-newTab
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ../chromeExtension-newTab.crx
