name: release_artifacts
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5

jobs:
  release-artifacts:
    name: Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Install zip
        run: sudo apt-get install zip
      - name: Generate zip
        run: |
          mkdir build 
          zip -r build/extension.zip .
      - name: Generate .crx
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: "build/extension.zip"
          crxFilePath: "build/newTab.crx"
          privateKey: "noSecretNeeded"
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/extension.zip
            build/newTab.crx
